In [39]:
import pandas as pd

df1 = pd.read_csv('Spin.dat', sep='\s+')
df1.to_parquet('Spin.parquet')

df = pd.read_parquet('Spin.parquet')
df = df.T
df

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
1,-1,-1,-1,1,-1,-1,1,1,1,1,...,-1,-1,-1,1,-1,-1,-1,1,-1,-1
2,1,1,1,-1,1,-1,-1,1,1,1,...,1,-1,-1,-1,-1,-1,-1,-1,1,-1
3,1,-1,-1,-1,-1,1,-1,-1,-1,1,...,-1,-1,-1,-1,1,1,1,-1,-1,-1
4,1,1,-1,1,1,1,-1,-1,-1,-1,...,1,-1,-1,-1,-1,-1,-1,-1,1,1
5,1,-1,1,-1,-1,1,-1,1,-1,1,...,1,-1,1,-1,-1,-1,-1,1,1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,1,-1,1,-1,1,1,1,-1,-1,-1,...,-1,1,-1,1,1,-1,-1,1,-1,-1
297,-1,1,1,-1,1,1,-1,1,-1,1,...,1,1,-1,-1,-1,-1,1,-1,1,1
298,1,1,1,-1,-1,1,-1,1,-1,-1,...,-1,1,-1,1,-1,-1,1,1,-1,-1
299,-1,-1,1,-1,1,-1,1,1,1,-1,...,-1,-1,1,1,-1,1,-1,-1,1,1
300,-1,1,-1,-1,-1,-1,1,1,1,1,...,1,-1,1,-1,-1,1,1,-1,1,-1

In [26]:
import numpy as np

In [32]:
media = []
for i in range(df.shape[0]):
    media.append(df.iloc[i].mean())
len(media)

300

In [35]:
media = [df.iloc[i].mean() for i in range(df.shape[0])]
np.mean(media)

0.4888019999999999

In [40]:
df.mean(axis=0)

0      -0.026667
1      -0.046667
2      -0.060000
3      -0.033333
4      -0.073333
          ...
9995   -0.013333
9996   -0.060000
9997   -0.013333
9998    0.006667
9999   -0.026667
Length: 10000, dtype: float64

In [43]:
df.mean(axis=1).to_list()

[-0.009,
 0.013,
 0.0038,
 0.0092,
 0.0082,
 -0.0156,
 -0.0058,
 0.0082,
 0.0254,
 0.0042,
 0.0032,
 -0.0104,
 -0.0082,
 0.0186,
 0.0172,
 0.0116,
 0.0202,
 -0.0016,
 -0.0154,
 -0.0134,
 0.0044,
 -0.003,
 0.0158,
 -0.0022,
 0.0128,
 -0.0106,
 0.015,
 0.008,
 -0.0062,
 0.0156,
 -0.5258,
 0.001,
 -0.5208,
 -0.5178,
 -0.0004,
 -0.5178,
 -0.5052,
 -0.012,
 -0.5074,
 -0.5136,
 -0.012,
 -0.5174,
 -0.5154,
 0.001,
 -0.5156,
 -0.51,
 -0.0042,
 -0.515,
 -0.5008,
 0.021,
 -0.5012,
 -0.53,
 0.0024,
 -0.5156,
 -0.5332,
 0.0104,
 -0.5162,
 -0.5262,
 -0.0044,
 -0.5136,
 -0.0006,
 0.0028,
 0.007,
 0.0128,
 -0.009,
 -0.0116,
 0.0138,
 -0.0128,
 -0.004,
 0.0014,
 0.0044,
 -0.0012,
 0.0034,
 -0.024,
 -0.0096,
 0.014,
 0.0036,
 -0.0098,
 -0.0058,
 0.002,
 0.017,
 -0.0094,
 0.0008,
 -0.0136,
 0.0092,
 -0.0158,
 -0.0044,
 0.015,
 -0.0114,
 -0.008,
 0.5134,
 -0.0154,
 0.5072,
 0.5084,
 -0.0062,
 0.5082,
 0.5044,
 -0.0022,
 0.5002,
 0.5144,
 -0.0092,
 0.5198,
 0.4992,
 -0.0054,
 0.5064,
 0.5134,
 -0.0332,
 0.5122,
 0.4856,
 -0.0042,
 0.5176,
 0.506,
 -0.005,
 0.5146,
 0.508,
 -0.0138,
 0.5198,
 0.501,
 -0.0126,
 0.5038,
 0.0048,
 -0.0024,
 0.0052,
 0.0114,
 -0.0024,
 -0.0006,
 -0.0046,
 -0.0094,
 0.0128,
 -0.0036,
 -0.0062,
 -0.0096,
 0.0098,
 0.0084,
 -0.0038,
 0.001,
 -0.0024,
 0.0066,
 -0.0016,
 -0.0012,
 -0.0064,
 0.0026,
 0.0078,
 -0.0038,
 0.0,
 -0.0004,
 -0.0198,
 -0.0176,
 0.0068,
 -0.0014,
 -0.0092,
 -0.5434,
 -0.0104,
 -0.0136,
 -0.5412,
 -0.0154,
 -0.0142,
 -0.5486,
 0.01,
 -0.0022,
 -0.5364,
 -0.0008,
 0.013,
 -0.552,
 0.0056,
 -0.0024,
 -0.5482,
 0.0028,
 -0.0152,
 -0.5454,
 0.0184,
 -0.0056,
 -0.5372,
 0.0132,
 -0.0028,
 -0.5452,
 0.0116,
 0.0166,
 -0.5498,
 0.0008,
 0.4988,
 -0.5544,
 0.5268,
 0.5062,
 -0.5494,
 0.5074,
 0.499,
 -0.5522,
 0.5166,
 0.5004,
 -0.5396,
 0.5114,
 0.503,
 -0.554,
 0.5132,
 0.513,
 -0.5638,
 0.5084,
 0.5032,
 -0.5494,
 0.4966,
 0.4994,
 -0.5548,
 0.5142,
 0.5154,
 -0.5544,
 0.4924,
 0.5046,
 -0.546,
 0.5098,
 0.0136,
 -0.0072,
 0.0044,
 0.0112,
 -0.008,
 -0.0134,
 0.011,
 -0.0182,
 0.0114,
 -0.0122,
 -0.0078,
 -0.0036,
 0.0048,
 0.0014,
 0.0122,
 0.0018,
 -0.0176,
 0.0044,
 -0.009,
 0.0126,
 0.0126,
 -0.0008,
 0.0236,
 -0.0082,
 0.0,
 0.0018,
 -0.0174,
 0.0188,
 0.0104,
 -0.0018,
 0.0098,
 -0.5742,
 0.0044,
 -0.0048,
 -0.57,
 -0.0072,
 0.0026,
 -0.5822,
 -0.004,
 0.0038,
 -0.5786,
 -0.0144,
 0.008,
 -0.574,
 0.0084,
 0.012,
 -0.5748,
 0.0138,
 -0.0006,
 -0.579,
 -0.0086,
 0.0082,
 -0.579,
 0.0078,
 0.0184,
 -0.5788,
 -0.004,
 0.002,
 -0.5812,
 0.0004,
 0.01,
 -0.0002,
 0.0056,
 -0.0148,
 0.014,
 0.002,
 0.0148,
 0.002,
 0.007,
 -0.0006,
 -0.003,
 -0.0084,
 -0.0004,
 0.0068,
 0.009,
 -0.0036,
 0.0006,
 0.0056,
 -0.0056,
 -0.0008,
 0.001,
 -0.0184,
 0.013,
 0.0108,
 -0.0074,
 -0.0096,
 -0.017,
 -0.0154,
 0.0178,
 -0.013]

In [ ]:
df2.